# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class ApiKey:
        type: str
        value: str
    class App:
        name: str
        stage: str
    class Chamados:
        name: str
        type: str
    class ChamadosApi:
        name: str
        type: str
    class ChamadosFila:
        type: str
        url: str
    class ChamadosTopico:
        arn: str
        type: str
    class DiscordWebhook:
        type: str
        value: str
    class Frontend:
        name: str
        type: str
    class GroqApiKey:
        type: str
        value: str
    class Relatorios:
        name: str
        type: str

