/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Chamados": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ChamadosApi": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ChamadosFila": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ChamadosTopico": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "DiscordWebhook": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GroqApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Relatorios": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}

import "sst"
export {}